set incsearch " Show partial search matches
set ignorecase " Ignore search cases 
set wildmenu " Tab completion for menus
set hlsearch " Highlight searches
set number relativenumber " Show relative line numbers
set scrolloff=1 " When to start showing text when scrolling
set laststatus=2
set backspace=indent,eol,start " Allow backspace to work as expected
set belloff=all
set nocompatible " Don't try to emulate vi
set noshowmode
set autoindent " Maintain indent of previous line
set smartindent " Slightly smart indenting
set splitbelow
set splitright
set showcmd " Show commands ad they are typed
syntax on
set termguicolors " Make most colorscheme work 

" General remaps
nnoremap <SPACE> <Nop>
let mapleader = " " 
nnoremap <leader>j <C-W><C-J>
nnoremap <leader>k <C-W><C-K>
nnoremap <leader>l <C-W><C-L>
nnoremap <leader>h <C-W><C-H>

" Show trailing white space
set list
set listchars=tab:\|\ ,trail:.,extends:>,precedes:<

" Simple netrw configs
let g:netrw_liststyle = 3
let g:netrw_winsize = 25
let g:netrw_browse_split = 3
map <leader>n :Vex<CR> " Open netrw

" ===== Plugins =====
call plug#begin('~/.vim/plugged')
" Generally useful plugins
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'jiangmiao/auto-pairs'
Plug 'alvan/vim-closetag'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'dense-analysis/ale' 
Plug 'sheerun/vim-polyglot'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-rooter'
call plug#end()

" ==================
" = Plugin Configs =
" ==================

" Separate plugin specific configs
source ~/.dotfiles/vim/coc.vim
source ~/.dotfiles/vim/fzf.vim
" source ~/.dotfiles/vim/nerdtree.vim

" Rooter conifgs
let g:rooter_patterns = ['.git']

" Airline configs
let g:airline_theme='deus'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tab_nr = 1
let g:airline#extensions#tabline#show_close_button = 1


" Emmet configs
let g:user_emmet_leader_key = ','
let g:user_emmet_install_global = 0
autocmd FileType html,css,eelixir EmmetInstall

" Closetag default config
" These are the file extensions where this plugin is enabled.
let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.eex'
