#!/usr/bin/env zsh
##### oh-my-zsh setup #####
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="kphoen"
source "$ZSH/oh-my-zsh.sh"

##### Env vars #####
# Set the default configuration file location used by many programs
export XDG_CONFIG_HOME="$HOME/.config"

# PATH Changes
# User binaries
export PATH="$HOME/bin:$PATH"
# System wide binaries
export PATH="/usr/local/bin:$PATH"
# Go binaries
export PATH="$PATH:$HOME/go/bin"

##### ZSH Configs #####
# Make vim bindings work for completions selection
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'l' vi-forward-char
# Case insensitive path-completion
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'
# List file details
zstyle ':completion:*' file-list all
DISABLE_MAGIC_FUNCTIONS=true

# Partial completion suggestions
zstyle ':completion:*' list-suffixes
zstyle ':completion:*' expand prefix suffix
autoload -Uz compinit && compinit

# Options
setopt auto_remove_slash # automatically remove slash from completions
setopt inc_append_history # save commands in history immediately
setopt share_history # share history between shells

##### Aliases #####
alias ls='ls -lah --color'

# Enable bat
[ -x "$(command -v bat)" ] && alias cat='bat --paging=never'

##### Source additional plugin configurations #####
source "$HOME/.dotfiles/zsh/plugins.zsh"

##### Source useful custom AWS CLI commands #####
AWS_COMMANDS_FILE="$HOME/.dotfiles/zsh/aws_commands.zsh"
[ -f "$AWS_COMMANDS_FILE" ] && source "$AWS_COMMANDS_FILE"

##### Source useful custom kubectl CLI commands #####
KUBECTL_COMMANDS_FILE="$HOME/.dotfiles/zsh/kubectl_commands.zsh"
[ -f "$KUBECTL_COMMANDS_FILE" ] && source "$KUBECTL_COMMANDS_FILE"

##### Work Specific Configs #####
WORK_CONFIGS_FILE="$HOME/.zshrc_work.zsh"
[ -f "$WORK_CONFIGS_FILE" ] && source "$WORK_CONFIGS_FILE"
